import { useState, useEffect } from "react";
import axios from "../api";


export default function Scorecard() {
  const [interviews, setInterviews] = useState([]);
  const [selected, setSelected] = useState("");
  const [scorecard, setScorecard] = useState(null);
  const [loading, setLoading] = useState(false);
  const [genLoading, setGenLoading] = useState(false);
  const token = localStorage.getItem("token");

  useEffect(() => {
    axios.get(`${API}/api/features/replay-list`, { headers: { Authorization: `Bearer ${token}` } })
      .then(r => setInterviews(r.data))
      .catch(() => {});
  }, []);

  const fetchScorecard = async () => {
    if (!selected) return;
    setLoading(true); setScorecard(null);
    try {
      const r = await axios.get(`${API}/api/features/scorecard/${selected}`, { headers: { Authorization: `Bearer ${token}` } });
      setScorecard(r.data);
    } catch (e) { alert("Error: " + (e.response?.data?.error || e.message)); }
    setLoading(false);
  };

  const downloadPDF = () => {
    if (!scorecard) return;
    setGenLoading(true);

    // Build HTML for print
    const html = `
      <!DOCTYPE html><html><head><title>Interview Scorecard</title>
      <style>
        body{font-family:Arial,sans-serif;padding:40px;color:#1f2937;max-width:800px;margin:0 auto}
        h1{color:#7c3aed;font-size:28px;text-align:center;border-bottom:3px solid #7c3aed;padding-bottom:12px}
        .score-circle{width:120px;height:120px;border-radius:50%;border:6px solid ${scorecard.interview.score>=7?"#22c55e":scorecard.interview.score>=5?"#f59e0b":"#ef4444"};display:flex;align-items:center;justify-content:center;margin:0 auto;font-size:36px;font-weight:800;color:${scorecard.interview.score>=7?"#22c55e":scorecard.interview.score>=5?"#f59e0b":"#ef4444"}}
        .section{background:#f9fafb;border-radius:10px;padding:20px;margin:20px 0;border-left:4px solid #7c3aed}
        .tag{display:inline-block;background:#ede9fe;color:#6d28d9;padding:4px 12px;border-radius:20px;font-size:13px;margin:4px}
        .green{color:#15803d;background:#dcfce7;border-left-color:#22c55e}
        .red{color:#b91c1c;background:#fee2e2;border-left-color:#ef4444}
        .meta{color:#6b7280;font-size:14px;text-align:center;margin:8px 0}
        h3{color:#7c3aed;margin-bottom:10px}
        p{line-height:1.7}
      </style></head><body>
      <h1>🎯 Interview Scorecard</h1>
      <div class="meta">Candidate: <strong>${scorecard.user.name}</strong> | ${scorecard.user.email}</div>
      <div class="meta">Date: ${new Date(scorecard.interview.date).toLocaleString()} | Topic: ${scorecard.interview.topic || "General"}</div>
      <div style="text-align:center;margin:24px 0">
        <div class="score-circle">${scorecard.interview.score}/10</div>
      </div>
      <div class="section"><h3>❓ Question</h3><p>${scorecard.interview.question}</p></div>
      <div class="section"><h3>💬 Your Answer</h3><p>${scorecard.interview.answer || "—"}</p></div>
      <div class="section"><h3>🤖 AI Feedback</h3><p>${scorecard.interview.feedback}</p></div>
      ${scorecard.insights.strengths?.length ? `<div class="section green"><h3>✅ Strengths</h3>${scorecard.insights.strengths.map(s=>`<span class="tag">${s}</span>`).join("")}</div>` : ""}
      ${scorecard.insights.weaknesses?.length ? `<div class="section red"><h3>⚠️ Areas for Improvement</h3>${scorecard.insights.weaknesses.map(s=>`<span class="tag">${s}</span>`).join("")}</div>` : ""}
      <div style="text-align:center;margin-top:40px;color:#9ca3af;font-size:12px">Generated by AI Interview Coach</div>
      </body></html>`;

    const w = window.open("", "_blank");
    w.document.write(html);
    w.document.close();
    w.print();
    setGenLoading(false);
  };

  const scoreColor = (s) => s >= 7 ? "#22c55e" : s >= 5 ? "#f59e0b" : "#ef4444";

  return (
    <div style={{ minHeight: "100vh", background: "linear-gradient(135deg,#0f0c29,#302b63,#24243e)", padding: 20, fontFamily: "sans-serif" }}>
      <div style={{ maxWidth: 750, margin: "0 auto" }}>
        <h1 style={{ color: "#a78bfa", fontSize: 28, textAlign: "center", marginBottom: 8 }}>📊 PDF Scorecard</h1>
        <p style={{ color: "#9ca3af", textAlign: "center", marginBottom: 30 }}>Generate a beautiful scorecard for any interview session</p>

        <div style={{ background: "rgba(255,255,255,0.05)", borderRadius: 16, padding: 24, marginBottom: 24 }}>
          <label style={{ color: "#c4b5fd", fontSize: 14, display: "block", marginBottom: 8 }}>Select Interview Session</label>
          <select value={selected} onChange={e => setSelected(e.target.value)}
            style={{ width: "100%", padding: "12px 14px", borderRadius: 10, border: "1px solid #4b5563", background: "#1f2937", color: "#fff", fontSize: 14, marginBottom: 16 }}>
            <option value="">-- Choose a session --</option>
            {interviews.map(iv => (
              <option key={iv._id} value={iv._id}>
                [{iv.score}/10] {iv.question?.slice(0, 60)}... ({new Date(iv.createdAt).toLocaleDateString()})
              </option>
            ))}
          </select>
          <button onClick={fetchScorecard} disabled={loading || !selected}
            style={{ width: "100%", padding: 14, borderRadius: 12, background: "linear-gradient(90deg,#7c3aed,#a21caf)", color: "#fff", border: "none", fontSize: 16, fontWeight: 700, cursor: "pointer" }}>
            {loading ? "⏳ Generating..." : "🔍 Generate Scorecard"}
          </button>
        </div>

        {scorecard && (
          <div style={{ background: "rgba(255,255,255,0.05)", borderRadius: 16, padding: 24 }}>
            {/* Header */}
            <div style={{ textAlign: "center", marginBottom: 24 }}>
              <div style={{ fontSize: 14, color: "#9ca3af" }}>Candidate: <strong style={{ color: "#f3f4f6" }}>{scorecard.user.name}</strong></div>
              <div style={{ fontSize: 12, color: "#6b7280" }}>{new Date(scorecard.interview.date).toLocaleString()}</div>
              <div style={{ width: 100, height: 100, borderRadius: "50%", border: `5px solid ${scoreColor(scorecard.interview.score)}`, display: "flex", alignItems: "center", justifyContent: "center", margin: "16px auto" }}>
                <div style={{ fontSize: 28, fontWeight: 800, color: scoreColor(scorecard.interview.score) }}>{scorecard.interview.score}/10</div>
              </div>
            </div>

            {/* Q + A + Feedback */}
            {[
              { label: "❓ Question", text: scorecard.interview.question, border: "#7c3aed" },
              { label: "💬 Your Answer", text: scorecard.interview.answer || "—", border: "#0ea5e9" },
              { label: "🤖 AI Feedback", text: scorecard.interview.feedback, border: "#22c55e" }
            ].map((s, i) => (
              <div key={i} style={{ background: "#1f2937", borderLeft: `4px solid ${s.border}`, borderRadius: 10, padding: 16, marginBottom: 14 }}>
                <div style={{ color: s.border, fontWeight: 700, fontSize: 13, marginBottom: 8 }}>{s.label}</div>
                <p style={{ color: "#f3f4f6", margin: 0, lineHeight: 1.7, fontSize: 14 }}>{s.text}</p>
              </div>
            ))}

            {/* Strengths & Weaknesses */}
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14, marginBottom: 20 }}>
              <div style={{ background: "rgba(34,197,94,0.1)", border: "1px solid rgba(34,197,94,0.3)", borderRadius: 12, padding: 16 }}>
                <div style={{ color: "#34d399", fontWeight: 700, marginBottom: 10 }}>✅ Strengths</div>
                {scorecard.insights.strengths?.map((s, i) => (
                  <div key={i} style={{ color: "#86efac", fontSize: 13, marginBottom: 6 }}>• {s}</div>
                ))}
              </div>
              <div style={{ background: "rgba(239,68,68,0.1)", border: "1px solid rgba(239,68,68,0.3)", borderRadius: 12, padding: 16 }}>
                <div style={{ color: "#f87171", fontWeight: 700, marginBottom: 10 }}>⚠️ To Improve</div>
                {scorecard.insights.weaknesses?.map((s, i) => (
                  <div key={i} style={{ color: "#fca5a5", fontSize: 13, marginBottom: 6 }}>• {s}</div>
                ))}
              </div>
            </div>

            <button onClick={downloadPDF} disabled={genLoading}
              style={{ width: "100%", padding: 14, borderRadius: 12, background: "linear-gradient(90deg,#059669,#0ea5e9)", color: "#fff", border: "none", fontSize: 16, fontWeight: 700, cursor: "pointer" }}>
              {genLoading ? "⏳ Opening..." : "📥 Download PDF Scorecard"}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
